---
title: "Hufkens_Documentation"
author: "Jinyan Yang"
date: "22 August 2019"
Modified: "20 Apr 2020"
output: html_document
---

This file documents the application and modification of the Hufken's model to PACE.

## Existing issues of V00
Evidently in the V00 model, the growth and plant transpiration both depend on the absolute value of soil moisture while senescence is independent of soil moisture. This lead to difficulty when rooting depth is unknown or varying. 

The issue is related to soil moisture bucket. Since the absolute soil moisture can vary from 0 to say 500 mm, assuming a 50% VWC for 1m soil, the range of growth rate thus can vary a lot. Such a large range makes the fitting inefficient and sometimes impossible. The start values and range of those parameters are also hard to guess since they do not carry clear ecological meanings. 

The sensitivity of growth to soil water is assumed to be linear. We know from the plant vulnerability and soil retention curves that the relationship is probably not linear. 

The lagged water availability is also questionable. Plants will almost respond on the next day. Assuming plant only growth for one day is also not ideal. 

The t dependence is weird. The solar radiation based pheno also does not work for winter species. The model also cannot account for C3 C4 to present in the same pasture but different time of year because of the Topt and baseline phenology based on radiation. 

## Growth and senescense depend on max E (v12)

We chose to the ‘maximum transpiration’ approach (Duursma et al., 2008). This allows a mechanism based prediction of soil water supply. Please see the separate document for how it’s calculated. In short, a max E can be calculated at each soil moisture based on plant hydraulic conductance and soil retention curve. Then it will be standardised to max E at stature soil moisture, to calculate the fraction of reduction, fw.

Growth changed to: 

$$G_{t} = f_{T,t} f_{w,t}  (1 - {V_{t} \over V_{max}}) $$
where FT,t is the temperature modifier.  

fw,t is the soil water modifier calculated as below:

### soil water potential 
$$\psi_{soil} = \psi_{sat}({\theta_{soil} \over \theta_{sat}})^{-b} $$

### soil conductivity
$$ k_s = k_{sat} ({\psi_{soil} \over \psi_{sat}})^{2+3/b} $$

### soil conductance
$$ C_{soil} = {R_l \over LAI} {2 \pi k_s \over log(r_{cyl}/{r_root})}$$

### conductance of the plant soil pathway

$$ {1\over C_{total}} = {1 \over C_{soil} } + {1 \over C_{plant} } $$

### E max
$$ E_{max} = C_{total} (\psi_{soil} - \psi_{plant.min}) $$

### fraction of water available
Since transpiration depends on plant-environment, Remko standarsed the Emax with a theoretical $E_{max.0}$ at $\psi_{soil} = 0$. 

I modified this standardisation by using $E_{max.sat}$ when $\psi_{soil} = \psi_{sat}$:

$$ f_{w,t} = {E_{max} \over E_{max.sat}} $$


### how does V12 work 
```{r, echo=FALSE,warning=F,message=F}
source('r/functions_mcmc_v12.r')
day.lag <- 2
source('r/pace_data_process.R')
# packages
library(doBy)
library(zoo)

gcc.met.pace.df.16 <- get.pace.func(gcc.met.pace.df,
                                    species.in = 'Luc',
                                    prep.in = 'Drought',
                                    temp.in ='Ambient')
gcc.met.pace.df.16 = gcc.met.pace.df.16[gcc.met.pace.df.16$Date<
                                          as.Date('2018-8-31'),]
gcc.met.pace.df.16$map=760
chain.fes = readRDS('cache/chain.Luc.Control.Ambient.rds')

  # # check acceptance so that the 
  burnIn = 10000
  acceptance = 1-mean(duplicated(chain.fes[-(1:burnIn),])) 
  # # see how it works#####
  par.df <- data.frame(#f.h = c(200,220,240,NA,NA),
    f.t.opt = c(10,15,20,NA,NA,NA),
    f.extract = c(0.05,0.075,0.1,NA,NA,NA),
    f.sec = c(0.05,0.1,0.15,NA,NA,NA),
    f.growth = c(0.1,0.2,0.3,NA,NA,NA))
  row.names(par.df) <- c('min','initial','max','fit','stdv','prop')
  par.df["fit",] <- colMeans(chain.fes[burnIn:nrow(chain.fes),])

  bucket.size = 300
  
hufken.pace.pred <- phenoGrass.func.v12(gcc.met.pace.df.16,
                                          f.h = 222,
                                          f.t.opt = par.df["fit",1],
                                          f.extract = par.df["fit",2],
                                          f.sec= par.df["fit",3],
                                          f.growth = par.df["fit",4],
                                          bucket.size = bucket.size,
                                          swc.wilt = 0.05 ,
                                          swc.capacity = 0.13 ,
                                          t.max = 45,
                                          day.lay = day.lag)
  # hufken.pace.pred$water.norm <- hufken.pace.pred$water.avi / (0.13-0.05)/300
  library(viridisLite)
  palette(viridis(8))
  par(mar=c(5,5,1,1))
  plot(cover~Date,data = hufken.pace.pred,type='b',pch=16,
       xlab=' ',ylab=expression(f[cover]),ylim=c(0,0.8),col = palette()[6])
  
  points(cover.hufken~Date,data = hufken.pace.pred,type='b',col=palette()[8],pch=16)
  
# par(new=T)
# 
# plot(vwc~Date,data = gcc.met.pace.df.16,ann=F,axes=F,type='s',col='lightskyblue')
# 
# par(new=T)
# 
# plot(swc.hufken~Date,data = gcc.met.pace.df.16, ann=F,axes=F,type='l',col='lightskyblue',lty='dashed')
```

Fig 1. V12 fitted to Luc Ambient Control. 

